config/routes.rb
Rails.application.routes.draw do

  root 'trips#index'

  resources :trips do
    resources :locations do
    	resources :addresses 
    end
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :location
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :trip
	has_one :address, dependent: :destroy
end

app/models/trip.rb
class Trip < ActiveRecord::Base
	has_many :locations, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationController < ApplicationController
  def index
  	@trip = Trip.find(params[:trip_id])
  	@location = @trip.locations
  end

  def show
  end

  def edit
  end

  def new
  	@trip = Trip.find(params[:trip_id])
  	@location = Location.new
  end

  def create
  	@trip = Trip.find(params[:trip_id])
  	@trip.locations.create(location_params)
  	redirect_to trip_locations_path(@trip)
  end

  private
  	def location_params
  		params.require(:location).permit(:name, :location_id)
  	end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :trip, except: [:index, :new, :create]

  def index
  	@trips = Trip.all
  end

  def show
    @trips = Trip.find(params[:id])
    @locations = Trip.locations
  end

  def new
  	@trip = Trip.new
  end

  def create
  	@trip = Trip.create(trip_params)
  	redirect_to trips_path
  end

  def edit

  end

  def update
  	@trip.update(trip_params)
  	redirect_to trips_path
  end

  def destroy
  	@trip.destroy
  	redirect_to trips_path
  end

  private
  	def trip_params
  		params.require(:trip).permit(:name, :start, :end, :location)
  	end

  	def trip
  		@trip = Trip.find(params[:id])
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TripTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/location/_form.html.erb
<%= form_for @trip.location do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name, placeholder: 'City/State', required: true %>
	<br />
	<%= f.submit :submit %>
<% end %>

app/views/location/edit.html.erb
<h1>Edit Locations</h1>

app/views/location/index.html.erb
<h1>Locations For: <= @trip.name %></h1>
<hr />

<% if @locations.any? %>
	<ul>
		<% @locations.each do |location| %>
			<li>
				<%= link_to location.name, trip_locations_path(@trip, location) %>
			</li>
		<% end %>
	<% else %>
		<h3>No locations yet. Please input one using the New Location link below.</h3>
	<% end %>

	<%= link_to 'New Location', new_trip_location_path(@trip) %>

app/views/location/new.html.erb
<h1>New Location</h1>
<hr />
<%= render(partial: 'form') %>

app/views/location/show.html.erb
<h1> <%= @trip.location.name %> </h1>

	<label>Trip Locations</label>
	<br />
	<h5> <%= @trip.location %> </h5>
	<br />
	

<%= link_to 'Add Trip Locations', new_trip_location_path(@trip) %>
<br />
<%= link_to 'Edit', edit_trip_path %>
<br />
<%= link_to 'Delete', trip_path, method: :delete, data: {confirm: 'Really delete this Trip?'} %>

app/views/trips/_form.html.erb
<%= form_for @trip do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name, placeholder: 'Trip Name', required: true %>
	<br />
	<%= f.label :start %>
	<%= f.date_field :start %>
	<br />
	<%= f.label :end %>
	<%= f.date_field :end %>
	<br />
	<%= f.submit :submit %>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing <%= @trip.name %></h1>
<hr />
<%= render(partial: 'form') %>

app/views/trips/index.html.erb
<h1>Trip Tracker</h1>
<hr />

<% @trips.each do |trip| %>
	<div class="inline">
		<h3>
			<%= link_to trip.name, trip_path(trip) %>
		</h3>
		<h5>
			Trip Location Count:
			<%= trip.locations.count %>
		</h5>
		<%= link_to 'Edit', edit_trip_path(trip) %>
		<br />
		<%= link_to 'Delete', trip_path(trip), method: :delete, data: {confirm: 'Really delete this Trip?'} %>
	</div>
<% end %>

<hr />

<button type='button'>
	<%= link_to 'Create Trip', new_trip_path %>
</button>

app/views/trips/new.html.erb
<h1>New Trip</h1>
<hr />
<%= render(partial: 'form') %>

app/views/trips/show.html.erb
<h1> <%= @trip.name %> </h1>

	<label>Start Date</label>
	<br />
	<h5> <%= @trip.start %> </h5>
	<br />
	<label>End Date</label>
	<br />
	<h5> <%= @trip.end %> </h5>
	<br />
	<h5> <%= @trip.locations %> </h5>

<%= link_to 'Add Trip Locations', new_trip_location_path(@trip) %>
<br />
<%= link_to 'Edit', edit_trip_path %>
<br />
<%= link_to 'Delete', trip_path, method: :delete, data: {confirm: 'Really delete this Trip?'} %>